// frontend/src/components/layout/Sidebar.tsx
import { NavLink, useParams } from "react-router-dom";

export function Sidebar() {
  const { name } = useParams<{ name: string }>();

  const links = [
    { to: `/projects/${name}`, label: "Workspace", end: true },
    { to: `/projects/${name}/settings`, label: "Settings" },
    { to: `/projects/${name}/activity`, label: "Activity" },
  ];

  return (
    <nav className="w-48 border-r border-gray-200 bg-white p-4 space-y-1">
      {links.map((link) => (
        <NavLink
          key={link.to}
          to={link.to}
          end={link.end}
          className={({ isActive }) =>
            `block px-3 py-2 rounded text-sm ${
              isActive ? "bg-blue-50 text-blue-700 font-medium" : "text-gray-700 hover:bg-gray-100"
            }`
          }
        >
          {link.label}
        </NavLink>
      ))}
    </nav>
  );
}

// frontend/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { page } from "$app/stores";

  let { projectName } = $props<{ projectName: string }>();

  const links = $derived([
    { href: `/projects/${encodeURIComponent(projectName)}`, label: "Workspace", exact: true },
    { href: `/projects/${encodeURIComponent(projectName)}/settings`, label: "Settings" },
    { href: `/projects/${encodeURIComponent(projectName)}/activity`, label: "Activity" },
  ]);
</script>

<nav class="w-40 p-3 space-y-0.5"
  style="background-color: var(--color-bg-raised); border-right: 1px solid var(--color-border);">
  {#each links as link}
    {@const isActive = link.exact
      ? $page.url.pathname === link.href
      : $page.url.pathname.startsWith(link.href)}
    <a href={link.href}
      class="block px-2.5 py-1.5 rounded-lg"
      style="font-size: 12px; {isActive
        ? `background-color: var(--color-pink-dark); color: white; font-weight: 500;`
        : `color: var(--color-text);`}"
    >
      {link.label}
    </a>
  {/each}
</nav>
