// frontend/src/lib/components/activity/VersionTimeline.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import type { EntryHistory } from "$lib/types";

  let { versions } = $props<{ versions: EntryHistory[] }>();
</script>

<div class="space-y-3">
  {#each versions as version}
    <div class="p-4 rounded-xl"
      style="background-color: var(--color-bg-raised); border: 1px solid var(--color-border);">
      <div class="flex items-center justify-between mb-2">
        <div class="text-xs" style="color: var(--color-text-muted);">
          {new Date(version.changed_at).toLocaleString()} ·
          <span class="rounded-full px-2 py-0.5"
            style="background-color: var(--color-pink); color: white;">
            {version.source}
          </span>
        </div>
        <form method="POST" action="?/restore" use:enhance>
          <input type="hidden" name="historyId" value={version.id} />
          <button type="submit" class="text-xs cursor-pointer"
            style="color: var(--color-link);">
            Restore this version
          </button>
        </form>
      </div>
      <pre class="text-xs font-mono rounded-lg p-3 whitespace-pre-wrap max-h-48 overflow-y-auto"
        style="background-color: var(--color-bg-muted); line-height: 1.6;"
      >{version.content}</pre>
    </div>
  {/each}
  {#if versions.length === 0}
    <p class="text-sm" style="color: var(--color-text-muted);">No version history</p>
  {/if}
</div>

// frontend/src/components/activity/VersionTimeline.tsx
import type { EntryHistory } from "../../types";

interface Props {
  versions: EntryHistory[];
  onRestore: (historyId: string) => void;
}

export function VersionTimeline({ versions, onRestore }: Props) {
  return (
    <div className="space-y-3">
      {versions.map((v) => (
        <div key={v.id} className="bg-white border rounded p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="text-xs text-gray-500">
              {new Date(v.changed_at).toLocaleString()} · {v.source}
            </div>
            <button
              onClick={() => onRestore(v.id)}
              className="text-xs text-blue-600 hover:underline"
            >
              Restore this version
            </button>
          </div>
          <pre className="text-xs font-mono bg-gray-50 rounded p-3 whitespace-pre-wrap max-h-48 overflow-y-auto">
            {v.content}
          </pre>
        </div>
      ))}
      {!versions.length && <p className="text-gray-400 text-sm">No version history</p>}
    </div>
  );
}
