// frontend/src/components/account/ConnectedAccounts.tsx
import { useAuth } from "../../lib/auth";

export function ConnectedAccounts() {
  const { signInWithOAuth } = useAuth();

  return (
    <div className="bg-white border rounded-lg p-4">
      <h3 className="font-medium mb-3">Connected Accounts</h3>
      <div className="space-y-2">
        <button
          onClick={() => signInWithOAuth("google")}
          className="w-full border border-gray-300 rounded px-4 py-2 text-sm hover:bg-gray-50 text-left"
        >
          Link Google Account
        </button>
        <button
          onClick={() => signInWithOAuth("github")}
          className="w-full border border-gray-300 rounded px-4 py-2 text-sm hover:bg-gray-50 text-left"
        >
          Link GitHub Account
        </button>
      </div>
    </div>
  );
}

// frontend/src/lib/components/account/ConnectedAccounts.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
</script>

<div class="p-4 rounded-xl"
  style="background-color: var(--color-bg-raised); border: 1px solid var(--color-border);">
  <h3 class="font-medium mb-3">Connected Accounts</h3>
  <div class="space-y-2">
    <form method="POST" action="?/connectOAuth" use:enhance>
      <input type="hidden" name="provider" value="google" />
      <button type="submit" class="w-full text-left rounded-lg px-4 py-2.5 text-sm cursor-pointer"
        style="border: 1px solid var(--color-border);">
        Link Google Account
      </button>
    </form>
    <form method="POST" action="?/connectOAuth" use:enhance>
      <input type="hidden" name="provider" value="github" />
      <button type="submit" class="w-full text-left rounded-lg px-4 py-2.5 text-sm cursor-pointer"
        style="border: 1px solid var(--color-border);">
        Link GitHub Account
      </button>
    </form>
  </div>
</div>
