// frontend-svelte/src/lib/components/layout/AppShell.svelte
<script lang="ts">
  import { enhance } from "$app/forms";

  let { user, children } = $props<{
    user: { id: string; email: string };
    children: import("svelte").Snippet;
  }>();
</script>

<div class="min-h-screen" style="background-color: var(--color-bg);">
  <header class="px-6 py-3 flex items-center justify-between"
    style="background-color: var(--color-bg-raised); border-bottom: 1px solid var(--color-border);">
    <a href="/" class="text-lg font-semibold" style="color: var(--color-text);">
      synapse
    </a>
    <div class="flex items-center gap-4">
      <span class="text-sm" style="color: var(--color-text-muted);">{user.email}</span>
      <a href="/account" class="text-sm" style="color: var(--color-accent);">Account</a>
      <form method="POST" action="/logout" use:enhance>
        <button type="submit" class="text-sm cursor-pointer"
          style="color: var(--color-text-muted);">
          Sign out
        </button>
      </form>
    </div>
  </header>
  <main>
    {@render children()}
  </main>
</div>

// frontend/src/components/layout/AppShell.tsx
import { Outlet, Link, useNavigate } from "react-router-dom";
import { useAuth } from "../../lib/auth";

export function AppShell() {
  const { user, signOut } = useAuth();
  const navigate = useNavigate();

  const handleSignOut = async () => {
    await signOut();
    navigate("/login");
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between">
        <Link to="/" className="text-lg font-semibold text-gray-900">
          Synapse
        </Link>
        <div className="flex items-center gap-4">
          <span className="text-sm text-gray-600">{user?.email}</span>
          <Link to="/account" className="text-sm text-blue-600 hover:underline">
            Account
          </Link>
          <button
            onClick={handleSignOut}
            className="text-sm text-gray-500 hover:text-gray-700"
          >
            Sign out
          </button>
        </div>
      </header>
      <main>
        <Outlet />
      </main>
    </div>
  );
}
