// frontend/src/components/workspace/EntryEditor.tsx
import { useState } from "react";

interface Props {
  initialContent?: string;
  initialPath?: string;
  initialTags?: string[];
  onSave: (path: string, content: string, tags: string[]) => void;
  onCancel: () => void;
  isNew?: boolean;
}

export function EntryEditor({ initialContent = "", initialPath = "", initialTags = [], onSave, onCancel, isNew }: Props) {
  const [path, setPath] = useState(initialPath);
  const [content, setContent] = useState(initialContent);
  const [tagsInput, setTagsInput] = useState(initialTags.join(", "));

  const handleSave = () => {
    const tags = tagsInput.split(",").map((t) => t.trim()).filter(Boolean);
    onSave(path, content, tags);
  };

  return (
    <div className="space-y-4">
      {isNew && (
        <input
          type="text"
          placeholder="Path (e.g., decisions/chose-react.md)"
          value={path}
          onChange={(e) => setPath(e.target.value)}
          className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
        />
      )}
      <textarea
        value={content}
        onChange={(e) => setContent(e.target.value)}
        className="w-full border border-gray-300 rounded px-3 py-2 text-sm font-mono min-h-[400px]"
        placeholder="Content (markdown)"
      />
      <input
        type="text"
        placeholder="Tags (comma-separated)"
        value={tagsInput}
        onChange={(e) => setTagsInput(e.target.value)}
        className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
      />
      <div className="flex gap-2">
        <button onClick={handleSave} className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-medium hover:bg-blue-700">
          Save
        </button>
        <button onClick={onCancel} className="text-gray-500 text-sm hover:text-gray-700">
          Cancel
        </button>
      </div>
    </div>
  );
}

// frontend-svelte/src/lib/components/workspace/EntryEditor.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import type { Entry } from "$lib/types";

  let { entry, projectName, isNew = false } = $props<{
    entry?: Entry | null;
    projectName: string;
    isNew?: boolean;
  }>();
</script>

<form method="POST" action="?/saveEntry" use:enhance={() => {
  return async ({ result, update }) => {
    if (result.type === "success" && result.data?.savedPath) {
      window.location.href = `/projects/${encodeURIComponent(projectName)}?path=${encodeURIComponent(result.data.savedPath as string)}`;
    } else {
      await update();
    }
  };
}} class="space-y-4">
  {#if isNew}
    <input type="text" name="path" placeholder="Path (e.g., decisions/chose-svelte.md)"
      required autofocus
      class="w-full rounded-lg px-3 py-2.5 text-sm"
      style="border: 1px solid var(--color-border);"
    />
  {:else}
    <input type="hidden" name="path" value={entry?.path ?? ""} />
    <div class="text-sm font-medium" style="color: var(--color-text-muted);">
      Editing: {entry?.path}
    </div>
  {/if}
  <textarea name="content" placeholder="Content (markdown)"
    class="w-full rounded-lg px-3 py-2.5 text-sm font-mono"
    style="border: 1px solid var(--color-border); min-height: 400px; line-height: 1.6;"
  >{entry?.content ?? ""}</textarea>
  <input type="text" name="tags" placeholder="Tags (comma-separated)"
    value={entry?.tags?.join(", ") ?? ""}
    class="w-full rounded-lg px-3 py-2.5 text-sm"
    style="border: 1px solid var(--color-border);"
  />
  <div class="flex gap-2">
    <button type="submit"
      class="rounded-lg px-4 py-2.5 text-sm font-medium text-white cursor-pointer"
      style="background-color: var(--color-accent);">
      Save
    </button>
    <a href="/projects/{encodeURIComponent(projectName)}{entry ? `?path=${encodeURIComponent(entry.path)}` : ''}"
      class="rounded-lg px-4 py-2.5 text-sm cursor-pointer"
      style="color: var(--color-text-muted);">
      Cancel
    </a>
  </div>
</form>
