// frontend/src/lib/components/sharing/InviteDialog.svelte
<script lang="ts">
  import { enhance } from "$app/forms";

  let { error, projectId } = $props<{ error?: string | null; projectId: string }>();
</script>

<form method="POST" action="?/addMember" use:enhance class="flex gap-2 items-end">
  <input type="hidden" name="projectId" value={projectId} />
  <input type="email" name="email" placeholder="Email address" required
    class="flex-1 rounded-lg px-3 py-2.5 text-sm"
    style="border: 1px solid var(--color-border);"
  />
  <select name="role"
    class="rounded-lg px-3 py-2.5 text-sm"
    style="border: 1px solid var(--color-border);">
    <option value="editor">Editor</option>
    <option value="viewer">Viewer</option>
  </select>
  <button type="submit"
    class="rounded-lg px-4 py-2.5 text-sm font-medium cursor-pointer"
    style="background-color: var(--color-accent); color: white;">
    Invite
  </button>
</form>
{#if error}
  <p class="mt-2 text-sm" style="color: var(--color-danger);">{error}</p>
{/if}

// frontend/src/components/sharing/InviteDialog.tsx
import { useState } from "react";
import { useAddMember } from "../../hooks/useMembers";

interface Props { projectId: string; }

export function InviteDialog({ projectId }: Props) {
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"editor" | "viewer">("editor");
  const [error, setError] = useState("");
  const addMember = useAddMember(projectId);

  const handleInvite = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    try {
      await addMember.mutateAsync({ email, role });
      setEmail("");
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <form onSubmit={handleInvite} className="flex gap-2 items-end">
      <input
        type="email"
        placeholder="Email address"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        className="flex-1 border border-gray-300 rounded px-3 py-2 text-sm"
        required
      />
      <select value={role} onChange={(e) => setRole(e.target.value as any)} className="border border-gray-300 rounded px-3 py-2 text-sm">
        <option value="editor">Editor</option>
        <option value="viewer">Viewer</option>
      </select>
      <button type="submit" className="bg-blue-600 text-white rounded px-4 py-2 text-sm">Invite</button>
      {error && <span className="text-red-600 text-sm">{error}</span>}
    </form>
  );
}
