// frontend/src/lib/components/sharing/MemberList.svelte
<script lang="ts">
import { enhance } from "$app/forms";
import type { ProjectMember } from "$lib/types";

let { members, projectId } = $props<{ members: ProjectMember[]; projectId: string }>();
</script>

<div class="space-y-2">
  {#each members as member}
    <div class="flex items-center justify-between p-3 rounded-xl"
      style="background-color: var(--color-bg-raised); border: 1px solid var(--color-border);">
      <div>
        <span class="text-sm">{member.email ?? member.user_id}</span>
        <span class="ml-2 text-xs rounded-full px-2 py-0.5"
          style="background-color: var(--color-accent); color: white;">
          {member.role}
        </span>
      </div>
      {#if member.role !== "owner"}
        <form method="POST" action="?/removeMember" use:enhance>
          <input type="hidden" name="projectId" value={projectId} />
          <input type="hidden" name="email" value={member.email ?? ""} />
          <button type="submit" class="text-xs cursor-pointer"
            style="color: var(--color-danger);">
            Remove
          </button>
        </form>
      {/if}
    </div>
  {/each}
</div>

// frontend/src/components/sharing/MemberList.tsx
import { useRemoveMember } from "../../hooks/useMembers";
import type { ProjectMember } from "../../types";

interface Props {
  projectId: string;
  members: ProjectMember[];
}

export function MemberList({ projectId, members }: Props) {
  const removeMember = useRemoveMember(projectId);

  return (
    <div className="space-y-2">
      {members.map((m) => (
        <div key={m.user_id} className="flex items-center justify-between bg-white border rounded p-3">
          <div>
            <span className="text-sm">{m.email ?? m.user_id}</span>
            <span className="ml-2 text-xs bg-gray-100 rounded px-1.5 py-0.5">{m.role}</span>
          </div>
          {m.role !== "owner" && (
            <button
              onClick={() => m.email && removeMember.mutate(m.email)}
              className="text-xs text-red-600 hover:underline"
            >
              Remove
            </button>
          )}
        </div>
      ))}
    </div>
  );
}
