// frontend-svelte/src/lib/components/sharing/ShareLinkManager.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import type { ShareLink } from "$lib/types";

  let { links, projectId } = $props<{ links: ShareLink[]; projectId: string }>();
  let copied = $state<string | null>(null);

  function copyLink(token: string) {
    navigator.clipboard.writeText(`${window.location.origin}/share/${token}`);
    copied = token;
    setTimeout(() => (copied = null), 2000);
  }
</script>

<div>
  <div class="flex gap-2 mb-4">
    <form method="POST" action="?/createLink" use:enhance>
      <input type="hidden" name="projectId" value={projectId} />
      <input type="hidden" name="role" value="viewer" />
      <button type="submit" class="rounded-lg px-3 py-2 text-sm cursor-pointer"
        style="border: 1px solid var(--color-border);">
        Create viewer link
      </button>
    </form>
    <form method="POST" action="?/createLink" use:enhance>
      <input type="hidden" name="projectId" value={projectId} />
      <input type="hidden" name="role" value="editor" />
      <button type="submit" class="rounded-lg px-3 py-2 text-sm cursor-pointer"
        style="border: 1px solid var(--color-border);">
        Create editor link
      </button>
    </form>
  </div>

  <div class="space-y-2">
    {#each links as link}
      <div class="flex items-center justify-between p-3 rounded-xl text-sm"
        style="background-color: var(--color-bg-raised); border: 1px solid var(--color-border);">
        <div>
          <span class="font-mono text-xs">{link.token.slice(0, 12)}...</span>
          <span class="ml-2 text-xs rounded-full px-2 py-0.5"
            style="background-color: var(--color-bg-muted);">
            {link.role}
          </span>
        </div>
        <div class="flex gap-3">
          <button onclick={() => copyLink(link.token)}
            class="text-xs cursor-pointer" style="color: var(--color-accent);">
            {copied === link.token ? "Copied!" : "Copy"}
          </button>
          <form method="POST" action="?/revokeLink" use:enhance class="inline">
            <input type="hidden" name="projectId" value={projectId} />
            <input type="hidden" name="token" value={link.token} />
            <button type="submit" class="text-xs cursor-pointer"
              style="color: var(--color-danger);">
              Revoke
            </button>
          </form>
        </div>
      </div>
    {/each}
    {#if links.length === 0}
      <p class="text-sm" style="color: var(--color-text-muted);">No share links yet</p>
    {/if}
  </div>
</div>

// frontend/src/components/sharing/ShareLinkManager.tsx
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";
import type { ShareLink } from "../../types";

interface Props { projectId: string; }

export function ShareLinkManager({ projectId }: Props) {
  const qc = useQueryClient();
  const { data: links = [] } = useQuery<ShareLink[]>({
    queryKey: ["share-links", projectId],
    queryFn: () => api.listShareLinks(projectId),
  });
  const createLink = useMutation({
    mutationFn: (role: string) => api.createShareLink(projectId, role),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["share-links", projectId] }),
  });
  const deleteLink = useMutation({
    mutationFn: (token: string) => api.deleteShareLink(projectId, token),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["share-links", projectId] }),
  });
  const [copied, setCopied] = useState<string | null>(null);

  const copyLink = (token: string) => {
    navigator.clipboard.writeText(`${window.location.origin}/share/${token}`);
    setCopied(token);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div>
      <div className="flex gap-2 mb-4">
        <button
          onClick={() => createLink.mutate("viewer")}
          className="border border-gray-300 rounded px-3 py-1.5 text-sm hover:bg-gray-50"
        >
          Create viewer link
        </button>
        <button
          onClick={() => createLink.mutate("editor")}
          className="border border-gray-300 rounded px-3 py-1.5 text-sm hover:bg-gray-50"
        >
          Create editor link
        </button>
      </div>
      <div className="space-y-2">
        {links.map((link) => (
          <div key={link.id} className="flex items-center justify-between bg-white border rounded p-3 text-sm">
            <div>
              <span className="font-mono text-xs">{link.token.slice(0, 12)}...</span>
              <span className="ml-2 text-xs bg-gray-100 rounded px-1.5 py-0.5">{link.role}</span>
            </div>
            <div className="flex gap-2">
              <button onClick={() => copyLink(link.token)} className="text-xs text-blue-600 hover:underline">
                {copied === link.token ? "Copied!" : "Copy"}
              </button>
              <button onClick={() => deleteLink.mutate(link.token)} className="text-xs text-red-600 hover:underline">
                Revoke
              </button>
            </div>
          </div>
        ))}
        {!links.length && <p className="text-gray-400 text-sm">No share links yet</p>}
      </div>
    </div>
  );
}
